apiVersion: v2
name: notes-app
description: A Helm chart for Notes App
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - notes
  - app
  - microservices
maintainers:
  - name: DevOps Team

