apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notes-app

resources:
  - ../../base/backend/deployment.yaml
  - ../../base/backend/service.yaml
  - ../../base/frontend/deployment.yaml
  - ../../base/frontend/service.yaml
  - ../../base/database/statefulset.yaml
  - ../../base/database/service.yaml
  - ingress.yaml

commonLabels:
  app: notes-app
  environment: dev

images:
  - name: notes-app-backend
    newTag: v1.0.0
  - name: notes-app-frontend
    newTag: v1.0.0

replicas:
  - name: notes-app-backend
    count: 2
  - name: notes-app-frontend
    count: 2

